#! /bin/sh

if [ ! $# -eq 2 ]
then
	echo "USAGE: ./goRoborobo NB_OF_EXP CONFIG_FILE"
else
	for cnt in `seq 1 $1`
	do
		echo =-=-=-=-=-=
		echo Exp. $cnt of $1
		echo =-=-=-=-=-=
		./roborobo -l $2
		echo -
	done
fi
